// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://erqisavlnwynkyfvnltb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVycWlzYXZsbnd5bmt5ZnZubHRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMDczNTQsImV4cCI6MjA2ODc4MzM1NH0.sIbSCgVcSW9JVslUuCCVoo0iT31uECDxchbpEJJ80_E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});